version: "3.8"
services:
  apache:
    container_name: "${COMPOSE_PROJECT_NAME}-server"
    build:
      context:  ./docker/apache
      args:
        gitusername: ${GIT_NAME}
        gitemail: ${GIT_EMAIL}
    links:
      - mysql
      - mongo
    networks:
      - aname
    ports:
      - "127.0.0.1:${HTML_PORT}:80"
      - "127.0.0.1:${HTML_SSL_PORT}:443"
    volumes:
      - ${DEV_LOCATION}:/var/www/html
      - ./docker/apache/user.ini:/usr/local/etc/php/conf.d/uploads.ini
  mysql:
    image: mysql:8.0.34
    container_name: "${COMPOSE_PROJECT_NAME}-mysql"
    networks:
      - aname
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DB_LOCATION}:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}-pma"
    networks:
      - aname
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "127.0.0.1:${MYSQL_PHPMYADMIN_PORT}:80"
  mongo:
    image: mongo:7.0
    container_name: "${COMPOSE_PROJECT_NAME}-mongo"
    networks:
      - aname
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_DB_LOCATION}/db:/data/db
      - ${MONGO_DB_LOCATION}/dev.archive:/Databases/dev.archive
      - ${MONGO_DB_LOCATION}/production:/Databases/production
networks:
  aname:
    driver: bridge