version: "3.8"
services:
  apache:
    container_name: apache
    build:
      context:  ./docker/apache
      args:
        gitusername: ${GIT_NAME}
        gitemail: ${GIT_EMAIL}
    links:
      - mysql
    networks:
      - aname
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"
      - "7000:7000"
      - "127.0.0.1:${HTML_PORT}:80"
      - "127.0.0.1:${HTML_SSL_PORT}:443"
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ${DEV_LOCATION}:/var/www/html
      - ./docker/apache/user.ini:/usr/local/etc/php/conf.d/uploads.ini
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    networks:
      - aname
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DB_LOCATION}:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    networks:
      - aname
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "127.0.0.1:${MYSQL_PHPMYADMIN_PORT}:80"
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_DB_LOCATION}/db:/data/db
      - ${MONGO_DB_LOCATION}/dev.archive:/Databases/dev.archive
      - ${MONGO_DB_LOCATION}/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:${MONGO_EXPRESS_PORT}:8081"
networks:
  aname:
    driver: bridge